# Generated by Django 5.1.2 on 2025-01-09 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duelists', '0004_alter_duelist_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTorneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('L', 'local'), ('OTS', 'OTS - Championship'), ('R', 'Remote Duel'), ('P', 'Modelo Personalizado')], max_length=3)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='torneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loja', models.CharField(max_length=100)),
                ('data_inicio', models.DateField(null=True)),
                ('data_fim', models.DateField(null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('protocole', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneio.categoriatorneio')),
                ('duelists', models.ManyToManyField(to='duelists.duelist')),
            ],
        ),
    ]
