# Generated by Django 5.1.2 on 2025-01-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0002_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneio',
            name='protocole',
        ),
        migrations.AddField(
            model_name='torneio',
            name='protocolo',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
