# Generated by Django 5.1.2 on 2025-01-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0003_remove_torneio_protocole_torneio_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='num_rodadas',
            field=models.IntegerField(default=1),
        ),
    ]
