# Generated by Django 5.1.2 on 2025-01-09 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duelists', '0005_duelist_points'),
        ('torneio', '0005_torneio_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneio',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='torneios_ganhos', to='duelists.duelist'),
        ),
    ]
