# Generated by Django 5.1.2 on 2025-01-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duelists', '0005_duelist_points'),
        ('torneio', '0007_torneio_identificador_alter_categoriatorneio_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneio',
            name='duelists',
            field=models.ManyToManyField(blank=True, null=True, to='duelists.duelist'),
        ),
    ]
