# Generated by Django 5.1.2 on 2025-01-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0008_alter_torneio_duelists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneio',
            name='protocolo',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
    ]
