# Generated by Django 5.1.2 on 2025-01-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneio', '0009_alter_torneio_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='horario_inicio',
            field=models.TimeField(null=True),
        ),
    ]
