# Generated by Django 5.1.2 on 2024-11-27 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duelists', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Duelists',
            new_name='Duelist',
        ),
    ]
