# Generated by Django 5.1.2 on 2024-11-28 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duelists', '0002_rename_duelists_duelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.CharField(max_length=50)),
                ('ydkcode', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('tournament_played', models.IntegerField(default=0)),
                ('tournament_won', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duelists.duelist')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
