# Generated by Django 5.1.2 on 2025-01-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duelists', '0003_deck_delete_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duelist',
            name='nickname',
            field=models.CharField(default='No Nickname', max_length=50),
        ),
    ]
