# Generated by Django 5.1.2 on 2025-01-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duelists', '0004_alter_duelist_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='duelist',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
